### PR TITLE
fix: fix modification of token info

### PR DESCRIPTION
**Pull request by Keith-CY**
1. fix typehash when the it's going to update token instead of create new one;
2. remove sudt(deprecated) from the token type list because sudt(deprecated) is actually never used.

Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/374#issuecomment-1926497337

### CODE REVIEW

**Review by WhiteMinds — APPROVED** [review]

**Comment by FrederLu** [comment]
image

Now there is only `Simple UDT` to choose from, and the pop-up window also displays it by default. Can it be selected by default when submitting?
Now user will be confused. All other required fields have been filled in, but the submit button cannot be clicked. The problem is that `Simple UDT` seems to be selected, but it still needs to be selected again in the drop-down list.

**Comment by FrederLu** [comment]
image

When using `Submit Token info`, if it is found that there is already email information, there will be an exception prompt.

@zmcNotafraid  The interface also needs to be adjusted.

**Comment by Keith-CY** [comment]
> image
> Now there is only `Simple UDT` to choose from, and the pop-up window also displays it by default. Can it be selected by default when submitting? Now user will be confused. All other required fields have been filled in, but the submit button cannot be clicked. The problem is that `Simple UDT` seems to be selected, but it still needs to be selected again in the drop-down list.

This happens after language is changed and is caused by unsetting status incorrectly, now it should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/249/commits/21e9cd7b6402ef5b9fc1a66cf9149f15667e809e

**Comment by Keith-CY** [comment]
> image
> When using `Submit Token info`, if it is found that there is already email information, there will be an exception prompt.
> 
> @zmcNotafraid The interface also needs to be adjusted.

It should be fixed by https://github.com/nervosnetwork/ckb-explorer/pull/1618 and its error message has been added by https://github.com/Magickbase/ckb-explorer-frontend/pull/249/commits/566354da5c416d70b356ae8911837a931c5b889e

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
