### PR TITLE
feat(bitcoin): add rgb++ tab

### PR DESCRIPTION
**Pull request by Keith-CY**
feat(rgb++): transaction prompt window

feat(rgb++): transaction prompt window

feat(rgb): fill data to the digest

fix(cell): fix the live cell style

fix(rgb): tx id name fix

feat(rgb++): only show when the address is rgb++ lock

fix(rgb++): integer should with 8 zeros when in the digest prompt window

style(rgb++): fix some style problem

feat(rgb++): language of leap in and leap out

Update .env.production.example

Co-authored-by: Chen Yu <keithwhisper@gmail.com>
Signed-off-by: daryl <sai9375@hotmail.com>

feat: add rgb

feat(rgb++): support btc address

fix(rgb++): name in digest

fix(rgb++): the btc address in digest wrapped

style(rgb++): change the way to compute the amount of rgb++ cell

style(rgb++): give the default value zero padding to decimal

style(rgb++): change rgbTransaction to isRGBTransaction

Update src/locales/zh.json

Co-authored-by: Chen Yu <keithwhisper@gmail.com>
Signed-off-by: daryl <sai9375@hotmail.com>

feat: Support btc tx and address (#269)

1. When the input is btc address, go to the address page
2. When the input is btc tx, goto tx page.

fix(asset_tab): rename asset tab label to the type name

fix: remove useless config

feat(rgb++): no records will be shown when no transfer in digest

fix(rgb++): some styled problem
1. rename isRGBTransaction to isRgbTransaction
2. use attribute to style class for positive and negetive
3. remove useless code from btc address component
4. show unknown token when name of udt is empty

style(rgb++): use exist close icon

fix(rgb++): add fixme for the rgb++ contract released

feat(rgb++): add loading to digest window prompt

fix(rgb++): fix the close button of digest modal

feat(rgb++): copyt the tx id when click on the digest

feat(rgb++): btc address encode type

### CODE REVIEW

**Comment by silySuper** [comment]
1.When scroll up and down browser，tips can not adjust. @devchenyan 

https://github.com/Magickbase/ckb-explorer-frontend/assets/25971273/e0f3df7a-56aa-43c6-b752-ecb2700a1ebe

2.It is better to add BTC address/BTC Seal TX id in search  result page.
截屏2024-03-21 11 38 01

**Comment by Keith-CY** [comment]
> 1.When scroll up and down browser，tips can not adjust. @devchenyan
> 
>  2024-03-21.09.46.25.mov 
> 2.It is better to add BTC address/BTC Seal TX id in search result page. 截屏2024-03-21 11 38 01

The placeholder should be added by https://github.com/Magickbase/ckb-explorer-frontend/pull/273/commits/05f3dbe1192ec10903e6eb9e666f6a791a1c7be1

**Comment by FrederLu** [comment]
## BTC Address

https://ckb-explorer-frontend-in-magickbase-repo-j8u2fjljf-magickbase.vercel.app/address/125K2xfiBdae42gSKiCGwi85Frpy1vHmGj?layout=lite
image
image
image

Found that the `RGB++` tag is missing on the Lite style.

---
image
image
image

https://mempool.space/tx/3b5e020d3c54919587e4391c296e83df51d083ecb2932416b77f6f08a9c20f10

The style needs to be adjusted, and `inputs` displays blank.

**Comment by devchenyan** [comment]
> 1.When scroll up and down browser，tips can not adjust. @devchenyan
> 
>  2024-03-21.09.46.25.mov 
> 2.It is better to add BTC address/BTC Seal TX id in search result page. 截屏2024-03-21 11 38 01

Issue 1 resolved

**Comment by Keith-CY** [comment]
Pasted Graphic 1
Name of some assets are not displayed, and NFT's count is displayed as `+1.00000000`, which should be `+1`

Abnormal layout
Pasted Graphic 2
Pasted Graphic 3

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-19ccvjcit-magickbase.vercel.app/address/3JtNmD58sXwJVbyQUrSmzc91cQ8X62vgrY?tx_status=committed

image
image

1、The `RGB++` label in the Lite of BTC address displays an error. Each label is displayed, which is inconsistent with `Professional`.
---

image
image

2、The `RGB++ Digest` pop-up window has abnormal layout (left and right/top spacing) on ​​the mobile terminal.
---

image
image

3、The style under the Lite tab on the mobile terminal needs to be adjusted.
---

**Comment by silySuper** [comment]
1.In address page,when address is long,view in new address format shows abnormal
截屏2024-03-22 15 59 10

2.Then copy icon aside commitment does not copy commitment but copy tx id.

https://github.com/Magickbase/ckb-explorer-frontend/assets/25971273/7c54957a-a287-41ad-91bb-be954991b142

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-3thpz9940-magickbase.vercel.app/address/37g2w4qzSVQrSh2wEt9djqHGBDUxkzeCXN
image
image
CKB information is missing under the overview of the BTC address page.

---
image
image

The `Bitcoin TXID` module needs to be integrated with the corresponding `Transaction` module.Now it seems that the two are independent and have nothing to do with each other.

**Comment by Daryl-L** [comment]
> 125K2xfiBdae42gSKiCGwi85Frpy1vHmGj?layout=lite

Problem 1 fixed.
Problem 3 fixed in fac300222fa23d06c49f1d0b4025c922b5151fcb

**Comment by Daryl-L** [comment]
> ## BTC Address
> https://ckb-explorer-frontend-in-magickbase-repo-j8u2fjljf-magickbase.vercel.app/address/125K2xfiBdae42gSKiCGwi85Frpy1vHmGj?layout=lite image image image
> 
> 1、Found that the `RGB++` tag is missing on the Lite style.
> 
> image image image
> https://mempool.space/tx/3b5e020d3c54919587e4391c296e83df51d083ecb2932416b77f6f08a9c20f10
> 
> 2、The style needs to be adjusted, and `inputs` displays blank(This is a coinbase transaction that mints new BTC.). Pay attention to the real RGB++ transaction, the real data must be a transfer transaction.
> 
> image
> 3、The effect in the video is missing when the mouse is hovering over the button. Button highlighting and mouse style changes.
> 
>  2024-03-21.16.43.14.mov 
> image
> `Address 125K2xfiBdae42gSKiCGwi85Frpy1vHmGj` image
> 
> 4、When there are different types of assets in the Live Cell, the overview needs to have tabs to distinguish the different assets. Referring to the UI, we found that the `Cells` tab text needs to be changed to `Live Cell (s)`, and pay attention to the order of the tabs.

Problem 4, 9d5a62d41883a8dd17555c30fd8ad818833a3162
The conclusion from discussion in channel, only `live cells` and the `RGB++` tab will be shown in BTC address page.

**Comment by Keith-CY** [comment]
> [ckb-explorer-frontend-in-magickbase-repo-3thpz9940-magickbase.vercel.app/address/37g2w4qzSVQrSh2wEt9djqHGBDUxkzeCXN](https://ckb-explorer-frontend-in-magickbase-repo-3thpz9940-magickbase.vercel.app/address/37g2w4qzSVQrSh2wEt9djqHGBDUxkzeCXN) image image CKB information is missing under the overview of the BTC address page.
> 
> image image
> The `Bitcoin TXID` module needs to be integrated with the corresponding `Transaction` module.Now it seems that the two are independent and have nothing to do with each other.
> 
> image image
> The style of the `Bitcoin TXID` module on the mobile terminal is inconsistent with the UI.
> 
> image image
> The text needs to be adjusted to the `Bitcoin TX: 6 Confirmed` style.At the same time, no confirmation message is displayed after the date.
> 
> image image
> The color of the hash part and the decimal point of the amount and the color of the following part must be consistent with the UI.
> 
> image image
> [mempool.space/address/bc1q2r8lq2jzx7auq6m6eedegeg7ae3muvpfcrf8cm](https://mempool.space/address/bc1q2r8lq2jzx7auq6m6eedegeg7ae3muvpfcrf8cm) The api timestamps are the same, but the page display times differ by 12 hours.

--------
For this point

> The text needs to be adjusted to the Bitcoin TX: 6 Confirmed style.At the same time, no confirmation message is displayed after the date.

I've connected to the designer that badge should only be for `type/label`(https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU?type=design&node-id=35067-23909&mode=dev#747825989), so the UI has been updated as follows

image

And the implementation as follows

image


The badge will be removed and `arrow` between `inputs/outputs` will be added later @FrederLu cc @Daryl-L

**Comment by FrederLu** [comment]
image
The tab order here should be Live Cell(s), RGB++.

---

**Comment by Daryl-L** [comment]
> image The tab order here should be Live Cell(s), RGB++.
> Transactions on testnet: "0x07b904a7c59c97e153877f53e35819fdfd06d1a782382e9de078917027016613", "0xcb609bde6668eaaf60e4f183516f1c69942868be56f780d3aa380170f3c877c1", "0xf7f2768293027c447c3c59ee427cd3b877eb2ee229fde62f43bb710154e4463a", "0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91", "0xa004500ef515ce5ff6df59089644b03ea7bd4714cd4275dbc4e490a72b088be1", "0x1240b9b082a51e86af53f2d6a8c4d0a6f5886c4440636abd1b6c4cd482b038a0", "0xa385f29f0d445db10cf30ab5fe2f269a7941277d3a9862694fe7482942fc9c0e", "0x469af194d5357c491904f0627bcc27698993430dde8f04d4e2b9649b52839fbc", "0xe7bd5f3d034ca5c2e79708309cf939e31914a08d4b798d97af5aafa6a4149886", "0x13178241a0acac6ecf57889bbf334db51e4277cd35d81a6e88693078892b8f75", "0x0c6cfe38089214edbe31b4a229e1fb5682c2c6c5d4453aa32a1cbd7148df9734"
> 
> https://ckb-explorer-frontend-in-magickbase-repo-hgsail3pb-magickbase.vercel.app/address/tb1qvt7p9g6mw70sealdewtfp0sekquxuru6j3gwmt image On the BTC address page, the data on the transaction tab is inconsistent with the list data.
> 
> image
> https://ckb-explorer-frontend-in-magickbase-repo-ifplq6ewt-magickbase.vercel.app/address/tb1qvt7p9g6mw70sealdewtfp0sekquxuru6j3gwmt
> 
> Clicking on the address jumps abnormally and does not jump to the correct address. Clicking on the BTC address will only jump to `https://mempool.space/testnet`, which requires the corresponding address page.

a2223f60bc3a102e8612e204c82340e7b7b0a701 
782f0809ca919852091cf1b18edc9a7b9ccf003c

**Comment by Daryl-L** [comment]
> https://ckb-explorer-frontend-in-magickbase-repo-19ccvjcit-magickbase.vercel.app/address/3JtNmD58sXwJVbyQUrSmzc91cQ8X62vgrY?tx_status=committed
> 
> image image
> ## 1、The `RGB++` label in the Lite of BTC address displays an error. Each label is displayed, which is inconsistent with `Professional`.
> image image
> ## 2、The `RGB++ Digest` pop-up window has abnormal layout (left and right/top spacing) on ​​the mobile terminal.
> image image
> ## 3、The style under the Lite tab on the mobile terminal needs to be adjusted.
> image
> ## 4、When the mouse is placed on the id behind the BTC address `Seal Tx On Bitcoin`, you need to change the mouse to a clickable style, and click to jump to the transaction details page.
> Cancel the click to copy information function.
> image
> ## 5、When the mouse is placed on the id behind "Seal Tx On Bitcoin" on the transaction details page, the mouse remains unchanged and there is no jump when clicking.

resolved

**Comment by Daryl-L** [comment]
> Pasted Graphic 1 Name of some assets are not displayed, and NFT's count is displayed as `+1.00000000`, which should be `+1`
> Abnormal layout Pasted Graphic 2 Pasted Graphic 3 image

resolved

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-git-7cb256-magickbase.vercel.app/transaction/0xad50d6393cda074279012a757ae1a980aeb677ee13f1bf990fa97d0ee226ade1

image

The two transfer records in the digest have the same address and can be aggregated.

---
https://ckb-explorer-frontend-in-magickbase-repo-git-7cb256-magickbase.vercel.app/transaction/0x5faa0a0d14970f29c384840a348d124d8dcbc1226eea7db614a4af6c363f2e18
image

https://ckb-explorer-frontend-in-magickbase-repo-git-7cb256-magickbase.vercel.app/address/tb1qvt7p9g6mw70sealdewtfp0sekquxuru6j3gwmt
image
Comparing the transaction page, the corresponding envelope icon is missing on the btc address page.

**Comment by Keith-CY** [comment]
Will be merged first to facilitate other teams' work. More fixes should be added as patch PRs

**Pull request merged**
