### PR TITLE
Feat: support export nervosdao csv

### PR DESCRIPTION
**Pull request by PainterPuppets**
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/592

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao?page=1
image

https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2024-05-26&tab=date
[exported-nervosdao-txs-2024-05-26-2024-05-27 (3).csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15464982/exported-nervosdao-txs-2024-05-26-2024-05-27.3.csv)
image
Export data according to the time range. It is expected that `0xaa6d0fad0e0943c60e748e4b9b8fdf86fc6349539ac0c782fc86299e6f0ca2c9` is the last data hash, but it is actually `0xdb6c74ff1416082bc7c5022b0fdf17b1b1c53 fb5251af0ea540d51212f640621`.

**Comment by PainterPuppets** [comment]
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao?page=1 image
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2024-05-26&tab=date [exported-nervosdao-txs-2024-05-26-2024-05-27 (3).csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15464982/exported-nervosdao-txs-2024-05-26-2024-05-27.3.csv) image 1、Export data according to the time range. It is expected that `0xaa6d0fad0e0943c60e748e4b9b8fdf86fc6349539ac0c782fc86299e6f0ca2c9` is the last data hash, but it is actually `0xdb6c74ff1416082bc7c5022b0fdf17b1b1c53 fb5251af0ea540d51212f640621`.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magi
> 
> image image
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-29&start-date=2024-05-28&tab=date image
> 
> 2、The data after the decimal point of `Amount` data needs to be displayed accurately except 0.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/zh/nervosdao?page=3 image
> 
> image
> 3、Compare `0x13cb480446a7a0309032dc6a306b66e7cb1ffce92ae21b829be1aaa0b81f55d1` data, `0x1b03163475d35fd090176ff8f336dc1a03908da142299b18fe6ca71 c599addc5` and `0x549c78c4f3ec4951551438e33a98b647b2b6f48cec24bb07cac99ae7b754dcf9` are also `Deposit` methods, but they will have an `Amount` of 0.00000001 exception information.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2022-07-05&tab=date [exported-nervosdao-txs-2022-07-05-2024-05-27.csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15465887/exported-nervosdao-txs-2022-07-05-2024-05-27.csv) image image
> 
> 4、The actual upper limit of exported data is greater than the `5000` in the prompt message.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/zh/nervosdao/depositor/export?end-date=2024-05-28&start-date=2010-01-01&tab=date [exported-nervosdao-depositors-2010-01-01-2024-05-28.csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15466133/exported-nervosdao-depositors-2010-01-01-2024-05-28.csv) image image
> 
> 5、The exported file is blank. At the same time, the table format must be in accordance with the prd.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/zh/nervosdao/depositor/export?end-date=2024-05-28&from-height=13397400&start-date=2020-01-01&tab=height&to-height=13397400 image
> 
> 6、Tip 500.

Currently the table data is provided by the back end, @rabbitz  can you help with that?

**Comment by rabbitz** [comment]
> 6. Tip 500


The request api is:

https://ckb-explorer-api-staging.magickbase.com/api/v1/dao_depositors/download_csv?start_date=1577808000000&end_date=1717054130645&start_number=13397400&end_number=13397400

The date and block number parameters appear here together，The request is abnormal.

**Comment by rabbitz** [comment]
fixed the issues 1, 2, and 3 . PR: https://github.com/nervosnetwork/ckb-explorer/pull/1901

**Comment by PainterPuppets** [comment]
> > 1、Export data according to the time range. It is expected that 0xaa6d0fad0e0943c60e748e4b9b8fdf86fc6349539ac0c782fc86299e6f0ca2c9 is the last data hash, but it is actually 0xdb6c74ff1416082bc7c5022b0fdf17b1b1c53 fb5251af0ea540d51212f640621.
> 
> image image
> 1、There is a problem with the data submitted by the front end. The normal range should be [2024-5-26 00:00:00,2024-5-27 23:59:59].
> 
> > https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2022-07-05&tab=date
> > [exported-nervosdao-txs-2022-07-05-2024-05-27.csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15465887/exported-nervosdao-txs-2022-07-05-2024-05-27.csv)
> > image
> > image
> > 4、The actual upper limit of exported data is greater than the 5000 in the prompt message.
> 
> 2、The number of 5,000 here refers to the 5,000 transactions, but how many DAO records may be included in a transaction, so the prompt information needs to be modified to `The earliest 5,000 transactions within the selected range will be exported, the number of records may exceed 5,000 because a single transaction can include multiple records.`
> 
> image
> 3、An exception occurred in the request to get data after switching input information between `date` and `block nubmer`.
> 
> @PainterPuppets

fixed

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000
image
Api prompt 504.

**Comment by PainterPuppets** [comment]
> https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000 image Api prompt 504.

I've got the same thing here, all other api seem to be fine, @rabbitz can you help look at it?

**Comment by rabbitz** [comment]
> > https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000 image Api prompt 504.
> 
> I've got the same thing here, all other api seem to be fine, @rabbitz can you help look at it?

The efficiency of the SQL query has some issues, and it is currently being optimized.

**Comment by FrederLu** [comment]
> > > 1、Export data according to the time range. It is expected that 0xaa6d0fad0e0943c60e748e4b9b8fdf86fc6349539ac0c782fc86299e6f0ca2c9 is the last data hash, but it is actually 0xdb6c74ff1416082bc7c5022b0fdf17b1b1c53 fb5251af0ea540d51212f640621.
> > 
> > 
> > image image
> > 1、There is a problem with the data submitted by the front end. The normal range should be [2024-5-26 00:00:00,2024-5-27 23:59:59].
> > > https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2022-07-05&tab=date
> > > [exported-nervosdao-txs-2022-07-05-2024-05-27.csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15465887/exported-nervosdao-txs-2022-07-05-2024-05-27.csv)
> > > image
> > > image
> > > 4、The actual upper limit of exported data is greater than the 5000 in the prompt message.
> > 
> > 
> > 2、The number of 5,000 here refers to the 5,000 transactions, but how many DAO records may be included in a transaction, so the prompt information needs to be modified to `The earliest 5,000 transactions within the selected range will be exported, the number of records may exceed 5,000 because a single transaction can include multiple records.`
> > image
> > 3、An exception occurred in the request to get data after switching input information between `date` and `block nubmer`.
> > @PainterPuppets
> 
> fixed

https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&from-height=1&start-date=2024-05-26&tab=date&to-height=5000

https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=5001&start-date=2020-01-01&tab=date&to-height=10000

After using `Block Number` to export the data, switch to `date` and find that the url also contains `to-height` information. This information should only appear when `Block Number` is used.  @PainterPuppets

**Comment by PainterPuppets** [comment]
> should

fixed

**Comment by PainterPuppets** [comment]
> > > > 1、Export data according to the time range. It is expected that 0xaa6d0fad0e0943c60e748e4b9b8fdf86fc6349539ac0c782fc86299e6f0ca2c9 is the last data hash, but it is actually 0xdb6c74ff1416082bc7c5022b0fdf17b1b1c53 fb5251af0ea540d51212f640621.
> > > 
> > > 
> > > image image
> > > 1、There is a problem with the data submitted by the front end. The normal range should be [2024-5-26 00:00:00,2024-5-27 23:59:59].
> > > > https://ckb-explorer-frontend-in-magickbase-repo-q0n2e3iyp-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&start-date=2022-07-05&tab=date
> > > > [exported-nervosdao-txs-2022-07-05-2024-05-27.csv](https://github.com/Magickbase/ckb-explorer-frontend/files/15465887/exported-nervosdao-txs-2022-07-05-2024-05-27.csv)
> > > > image
> > > > image
> > > > 4、The actual upper limit of exported data is greater than the 5000 in the prompt message.
> > > 
> > > 
> > > 2、The number of 5,000 here refers to the 5,000 transactions, but how many DAO records may be included in a transaction, so the prompt information needs to be modified to `The earliest 5,000 transactions within the selected range will be exported, the number of records may exceed 5,000 because a single transaction can include multiple records.`
> > > image
> > > 3、An exception occurred in the request to get data after switching input information between `date` and `block nubmer`.
> > > @PainterPuppets
> > 
> > 
> > fixed
> 
> https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/nervosdao/transaction/export?end-date=2024-05-27&from-height=1&start-date=2024-05-26&tab=date&to-height=5000
> 
> https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=5001&start-date=2020-01-01&tab=date&to-height=10000
> 
> After using `Block Number` to export the data, switch to `date` and find that the url also contains `to-height` information. This information should only appear when `Block Number` is used. @PainterPuppets

fixed

**Comment by FrederLu** [comment]
> > > https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000 image Api prompt 504.
> > 
> > 
> > I've got the same thing here, all other api seem to be fine, @rabbitz can you help look at it?
> 
> The efficiency of the SQL query has some issues, and it is currently being optimized.

https://ckb-explorer-frontend-in-magickbase-repo-8j78rfifq-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-05-27&start-date=2024-05-26&tab=date

`Depositors` data export interface problem still exists.

At the same time, has the data display logic in `/Withdraw request/Withdraw Finalization` exported data by `Depositors` been confirmed?  @Sven-TBD

**Comment by Keith-CY** [comment]
> > > > [ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000](https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000) image Api prompt 504.
> > > 
> > > 
> > > I've got the same thing here, all other api seem to be fine, @rabbitz can you help look at it?
> > 
> > 
> > The efficiency of the SQL query has some issues, and it is currently being optimized.
> 
> [ckb-explorer-frontend-in-magickbase-repo-8j78rfifq-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-05-27&start-date=2024-05-26&tab=date](https://ckb-explorer-frontend-in-magickbase-repo-8j78rfifq-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-05-27&start-date=2024-05-26&tab=date)
> 
> `Depositors` data export interface problem still exists.
> 
> At the same time, has the data display logic in `/Withdraw request/Withdraw Finalization` exported data by `Depositors` been confirmed? @Sven-TBD

Please check

**Comment by FrederLu** [comment]
Request URL:
https://ckb-explorer-api-staging.magickbase.com/api/v1/dao_depositors/download_csv?start_date=1719763200000&end_date=1719849599999
image

Request URL:
https://ckb-explorer-api-staging.magickbase.com/api/v1/dao_depositors/download_csv?start_number=13757249&end_number=13761121
image


The api prompts an exception.

**Comment by rabbitz** [comment]
> > > > > > [ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000](https://ckb-explorer-frontend-in-magickbase-repo-amp0tefjo-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-06-03&from-height=1&start-date=2020-01-01&tab=date&to-height=5000) image Api prompt 504.
> > > > > 
> > > > > 
> > > > > I've got the same thing here, all other api seem to be fine, @rabbitz can you help look at it?
> > > > 
> > > > 
> > > > The efficiency of the SQL query has some issues, and it is currently being optimized.
> > > 
> > > 
> > > [ckb-explorer-frontend-in-magickbase-repo-8j78rfifq-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-05-27&start-date=2024-05-26&tab=date](https://ckb-explorer-frontend-in-magickbase-repo-8j78rfifq-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-05-27&start-date=2024-05-26&tab=date)
> > > `Depositors` data export interface problem still exists.
> > > At the same time, has the data display logic in `/Withdraw request/Withdraw Finalization` exported data by `Depositors` been confirmed? @Sven-TBD
> > 
> > 
> > Please check @Sven-TBD
> 
> @FrederLu Confirmed with Chen, I have no question on the export function and we can put it on the Depositors Tab. If you have any questions , you can still ask me about it. When this feature pass the test, @PainterPuppets could merge it.

refactor pr: 

> Request URL: https://ckb-explorer-api-staging.magickbase.com/api/v1/dao_depositors/download_csv?start_date=1719763200000&end_date=1719849599999 image
> 
> Request URL: https://ckb-explorer-api-staging.magickbase.com/api/v1/dao_depositors/download_csv?start_number=13757249&end_number=13761121 image
> 
> The api prompts an exception.

refactor pr: https://github.com/nervosnetwork/ckb-explorer/pull/2037

**Comment by FrederLu** [comment]
> refactor pr: [nervosnetwork/ckb-explorer#2037](https://github.com/nervosnetwork/ckb-explorer/pull/2037) @FrederLu

https://ckb-explorer-frontend-in-magickbase-repo-njk190r6m-magickbase.vercel.app/en/nervosdao/depositor/export?from-height=13838820&tab=height&to-height=13839319

image


According to this export, these two data are incorrect, the calculation is 103749 and 535.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
