### PR TITLE
feat(btc): add op return

### PR DESCRIPTION
**Pull request by Daryl-L**
https://github.com/Magickbase/ckb-explorer-public-issues/issues/636

### CODE REVIEW

**Comment by FrederLu** [comment]
https://mempool.space/testnet/tx/7bc10f67d40b13f4eec1b6b3f041e945696443b450b4fbbc55d4c044b6a681a6
image

https://ckb-explorer-frontend-in-magickbase-repo-oox4vjxsu-magickbase.vercel.app/transaction/0x1dc8527ffccb9ed8330c299c4018552508667ac9d5f29eeae802b4f9eace7c5a
image

Is `OP RETURN` displayed here or does it need to display the complete `OP_RETURN Yn :;$< C "Dѐ` information like on `https://mempool.space/`?   cc @Sven-TBD

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067%3A20864&t=Rcem2oAZ16TjqGty-1
image

**Comment by Daryl-L** [comment]
> Yes we want some more info here , on the proposal, it looks like this image cc @Kirl70

It's commitment, which is displayed over head. and the decode of this is meaningless

**Comment by Daryl-L** [comment]
> > > Yes we want some more info here , on the proposal, it looks like this image cc @Kirl70
> > 
> > 
> > It's commitment, which is displayed over head. and the decode of this is meaningless
> 
> We can add it here, coz it's related with the RGB++ tx. And I guess this message is already included in the envelop icon. @Daryl-L Could you move it to this new place? We can extend the time of this issue, if you could add this feature here. image

Do you mean move the commitment here, and no longer display on the right of the btc tx id?

**Comment by Keith-CY** [comment]
> > > > Yes we want some more info here , on the proposal, it looks like this image cc @Kirl70
> > > 
> > > 
> > > It's commitment, which is displayed over head. and the decode of this is meaningless
> > 
> > 
> > We can add it here, coz it's related with the RGB++ tx. And I guess this message is already included in the envelop icon. @Daryl-L Could you move it to this new place? We can extend the time of this issue, if you could add this feature here. image
> 
> Do you mean move the commitment here, and no longer display on the right of the btc tx id?

@Sven-TBD please check

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
