### PR TITLE
feat: hide script item from list if its deployment info is not set

### PR DESCRIPTION
**Pull request by Keith-CY**

### CODE REVIEW

**Review by WhiteMinds — APPROVED** [review]

**Review by WhiteMinds — APPROVED** [review]
The `{script ? (...) : null}` in the following code can be directly changed to `(...)` .

**Comment by Keith-CY** [comment]
> The `{script ? (...) : null}` in the following code can be directly changed to `(...)` .

I can get the point but I didn't find corresponding code

**Comment by WhiteMinds** [comment]
> I can get the point but I didn't find corresponding code

https://github.com/Magickbase/ckb-explorer-frontend/pull/140/files#diff-e88da1105bbd0d05a526c1ad5da6e9361e6c5ee3fe3e97a31c301e0332272fc6R230-R240

**Comment by Keith-CY** [comment]
> > I can get the point but I didn't find corresponding code
> 
> [#140 (files)](https://github.com/Magickbase/ckb-explorer-frontend/pull/140/files#diff-e88da1105bbd0d05a526c1ad5da6e9361e6c5ee3fe3e97a31c301e0332272fc6R230-R240)

Updated by https://github.com/Magickbase/ckb-explorer-frontend/pull/140/commits/fdc6fd6cf587bcec367cd085f5b0901ba17bc11a

**Review by WhiteMinds — APPROVED** [review]

**Pull request merged**
