### PR TITLE
Token api

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR adds entries to submit sudt token info

1. submit token info on token list page: https://ckb-explorer-frontend-in-magickbase-repo-git-7593de-magickbase.vercel.app/tokens
2. submit token info in footer
3. edit token info on token info page: https://ckb-explorer-frontend-in-magickbase-repo-git-7593de-magickbase.vercel.app/sudt/0x0da0f83ca0d43a1796c411a65e8bbcf1edb2581fed5d513510c7e1729440c0c4
4. update token info template when users update nft info on nft collection page: https://ckb-explorer-frontend-in-magickbase-repo-git-7593de-magickbase.vercel.app/nft-collections

image
image

---
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/374

### CODE REVIEW

**Comment by Keith-CY** [comment]
Please have a review @Daryl-L @PainterPuppets @WhiteMinds

**Comment by FrederLu** [comment]
image

Unable to click the `Logo` button and upload images.

---
image
Clicking the `Submit Token Info` button on the `NFT Collection` page cannot bring up the pop-up window.

**Comment by FrederLu** [comment]
image
image
image

When the page is in Chinese, it needs to be Chineseized when `Submit Token Info` and `Modify Token Info` trigger prompts.

---
image
image

Operation on the phone `Submit token Info`, click` args` and `name` to indicate the information position will be shifted.

---
image
image
image

1. `Modify token info` Mouse hover`Report` Lack of UI styles.
2. There is no reaction when clicking the `Report` button.   It is expected that the desktop mail application needs to be called or there will be a second confirmation of the pop -up window to inform the user information.   @Sven-TBD 


---
https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/35ba8eb8-8baf-44f5-94ce-2ee38a36f4ae

After clicking on the `usDT` details, and then clicking on the `Inscription` details, the `Modify Token Info` button information will be displayed in an instant. It feels like a page cache when it feels.

**Comment by Keith-CY** [comment]
> 1. A default prompt can be given in the selection box, which is currently blank.
> 2. The location of the drop-down list button can refer to the UI draft style.

It's caused by missing of the default selected item, but the first item should be selected. I've tried but cannot reproduce it, which URL should I go?

> When the page is in Chinese, it needs to be Chineseized when Submit Token Info and Modify Token Info trigger prompts.

Will be updated after I get `error codes` from the backend developers

> Operation on the phone Submit token Info, click args and name to indicate the information position will be shifted.

The popup is displayed by the browsers so it cannot be controlled by code.

> Modify token info Mouse hoverReport Lack of UI styles.

Will be updated soon

**Comment by Keith-CY** [comment]
Mentioning the style of tooltip, it was reused from an existing component.
Now I found the style of tooltip has been updated globally
image
image

So I'd suggest opening a specific issue to update the `tooltip component` globally. One task, one issue, one PR for clarity.

cc @FrederLu

**Comment by FrederLu** [comment]
>> 1. A default prompt can be given in the selection box, which is currently blank.
>> 2. The location of the drop-down list button can refer to the UI draft style.
>
>It's caused by missing of the default selected item, but the first item should be selected. I've tried but cannot reproduce it, which URL should I go?

image

Already expected in the latest preview.

**Comment by Keith-CY** [comment]
image
Error messages have been internationalized and will be deployed soon

**Comment by FrederLu** [comment]
> > Operation on the phone Submit token Info, click args and name to indicate the information position will be shifted.
> 
> The popup is displayed by the browsers so it cannot be controlled by code.

Now, will a pop-up window appear when ‘Report’ is clicked?  But it didn't appear to me. Do I need to set it up on the browser?

**Comment by FrederLu** [comment]
> image
> Unable to click the `Logo` button and upload images.
> 
> image
> Clicking the `Submit Token Info` button on the `NFT Collection` page cannot bring up the pop-up window.

Let’s also look at the issues here.

**Comment by Keith-CY** [comment]
> > image
> > Unable to click the `Logo` button and upload images.
> > image
> > Clicking the `Submit Token Info` button on the `NFT Collection` page cannot bring up the pop-up window.
> 
> [#210 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/210#issuecomment-1918555188)
> 
> Let’s also look at the issues here.

It's expected to invoke the email client to submit NFT info because NFT information is not covered in the form.

Submission of NFT info was done by sending an email, so I kept it, as mentioned as point 4 in https://github.com/Magickbase/ckb-explorer-frontend/pull/210#issue-2083369307

**Comment by FrederLu** [comment]
> It's expected to invoke the email client to submit NFT info because NFT information is not covered in the form.
> 
> Submission of NFT info was done by sending an email, so I kept it, as mentioned as point 4 in [#210 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/210#issue-2083369307)


https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/a633203e-2180-4ccc-8ade-ba13c9d0db96


If we use email to submit information, this entry should be retained, but now after clicking and reopening the page, nothing happens.

**Comment by FrederLu** [comment]
image
image

User's `Report` template style can refer to prd optimization.

**Comment by Keith-CY** [comment]
> image image
> User's `Report` template style can refer to prd optimization.

This is what pre-filled in my e-mail
image

May I know which URL you were visiting so I can try to reproduce it.

**Comment by FrederLu** [comment]
>May I know which URL you were visiting so I can try to reproduce it.

https://ckb-explorer-frontend-in-magickbase-repo-8t0l9vdvp-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463

https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/b5b2dad9-ed34-42dc-891e-a9752f56d8e9

There is no special link operation, but the templates I see when I click `Report` are connected together.

**Comment by Keith-CY** [comment]
> > May I know which URL you were visiting so I can try to reproduce it.
> 
> [ckb-explorer-frontend-in-magickbase-repo-8t0l9vdvp-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463](https://ckb-explorer-frontend-in-magickbase-repo-8t0l9vdvp-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463)
> 
>  2024-02-02.17.39.46.mov 
> There is no special link operation, but the templates I see when I click `Report` are connected together.

I can reproduce this case by the URL you've provided. It should be out of date and please try the template by the preview URL in the second message
https://github.com/Magickbase/ckb-explorer-frontend/pull/210#issuecomment-1893320836

**Comment by FrederLu** [comment]
> > > May I know which URL you were visiting so I can try to reproduce it.
> > 
> > 
> > [ckb-explorer-frontend-in-magickbase-repo-8t0l9vdvp-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463](https://ckb-explorer-frontend-in-magickbase-repo-8t0l9vdvp-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463)
> > 2024-02-02.17.39.46.mov
> > There is no special link operation, but the templates I see when I click `Report` are connected together.
> 
> I can reproduce this case by the URL you've provided. It should be out of date and please try the template by the preview URL in the second message [#210 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/210#issuecomment-1893320836)

image

Well, that was a problem with my previous link, and the style has been modified on the new preview.

**Comment by Keith-CY** [comment]
> After clicking on the usDT details, and then clicking on the Inscription details, the Modify Token Info button information will be displayed in an instant. It feels like a page cache when it feels.

The crash-like flash is caused by loading status, the `modify token info` button is displayed by default, and hidden when the type of udt is confirmed to be an inscription after data is fetched.

Commit https://github.com/Magickbase/ckb-explorer-frontend/pull/210/commits/2f840592d3b7e04233cb3ef09910d9b40f41b7a9 adds a loading effect to avoid the flash

**Comment by FrederLu** [comment]
The known issues discovered have basically been resolved, and there are still a few issues for the time being.

image
image
image

The length of the Chinese/English `Confirm` button will become longer when clicked, and there is an additional `..` after the text.

---
https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/738c2b44-5bbd-4b4f-a7e7-9b9e513600a1

The `Token Type` input style is abnormal when switching between Chinese and English without refreshing the page.

---
image

There is no response when clicking the `Upload` button.

---
image

Confirm the template style submitted here and whether there is a Chinese template. @Sven-TBD

**Comment by Keith-CY** [comment]
> The length of the Chinese/English Confirm button will become longer when clicked, and there is an additional .. after the text.

> The Token Type input style is abnormal when switching between Chinese and English without refreshing the page.

Button width and default selected token type between EN and ZH pages should be fixed by commits https://github.com/Magickbase/ckb-explorer-frontend/pull/210/commits/5713401b2c56893cc4759e0c240e88916e84730e and https://github.com/Magickbase/ckb-explorer-frontend/pull/210/commits/6730b4042f5ef61863f01dedb6ef66d50350381c

---

> There is no response when clicking the Upload button.

I cannot reproduce this case, could you send me the URL to have a try

**Comment by FrederLu** [comment]
> > There is no response when clicking the Upload button.
> 
> I cannot reproduce this case, could you send me the URL to have a try

Submit Token Info
https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/tokens

Modify Token Info
https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463

**Comment by Keith-CY** [comment]
> > > There is no response when clicking the Upload button.
> > 
> > 
> > I cannot reproduce this case, could you send me the URL to have a try
> 
> Chrome version 103.0.5060.114 (official version) (arm64)
> 
> Submit Token Info [ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/tokens](https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/tokens)
> 
> Modify Token Info [ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463](https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463)

Both links work well for me, need help from @Sven-TBD @WhiteMinds

**Comment by Sven-TBD** [comment]
I dont think it's necessary to provide a Chinese version. On template, do we need the NFT description as well? @zmcNotafraid

**Comment by Sven-TBD** [comment]
> > > > There is no response when clicking the Upload button.
> > > 
> > > 
> > > I cannot reproduce this case, could you send me the URL to have a try
> > 
> > 
> > Chrome version 103.0.5060.114 (official version) (arm64)
> > Submit Token Info [ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/tokens](https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/tokens)
> > Modify Token Info [ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463](https://ckb-explorer-frontend-in-magickbase-repo-yhd60tq5i-magickbase.vercel.app/sudt/0x5fbce7d80b8f9db63e7b383d25ef14a8f96e181205a9901ff4736d79368d2463)
> 
> Both links work well for me, need help from @Sven-TBD @WhiteMinds

Me too, pop up normally

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
