### PR TITLE
Refactor: CSS responsive breakpoints

### PR DESCRIPTION
**Pull request by WhiteMinds**
Refs: https://github.com/Magickbase/ckb-explorer-public-issues/issues/489

Also, there are some style modifications involved:

### Before:
image

### After:
image

### Before:
image

### After:
image

### Before:
image

### After:
image

### Before:
image
image

### After:
image
image

### Before:
image
image

### After:
image
image

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Already one dev approved, maybe it's time to invite testers to verify the layout

**Comment by FrederLu** [comment]
Chrome version used
image

1、The top/bottom/left/right spacing of the layout in the red box of the mobile screenshot is too large, and you need to check the UI adjustment.

image
image

---
2、Compared with the previous pictures in NFT info, it seems that they are not expanded and displayed according to the corresponding proportion of the picture.

Before： https://pudge.explorer.nervos.org/nft-info/0x951dd6704ef1bac2fe1ab347d39d8f65a3b48dc75fe3cdc983aeaefd1bfa3467/59331
After：https://ckb-explorer-frontend-in-magickbase-repo-i9hwtwjn7-magickbase.vercel.app/nft-info/0x951dd6704ef1bac2fe1ab347d39d8f65a3b48dc75fe3cdc983aeaefd1bfa3467/59331

PC：
image
image
Mobile：
imageimage

**Comment by WhiteMinds** [comment]
> 1、The top/bottom/left/right spacing of the layout in the red box of the mobile screenshot is too large, and you need to check the UI adjustment.

Updated, now effect:

image

image


> 2、Compared with the previous pictures in NFT info, it seems that they are not expanded and displayed according to the corresponding proportion of the picture.

The behavior on both desktop and mobile devices is as expected. Low-resolution images will no longer be forcibly stretched. Normal high-resolution images in portrait orientation will be displayed as follows on mobile devices:

image

Currently, this image appears more like the following representation of a low-resolution image that is not forcibly stretched:

image

**Review by FrederLu — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please resolve conflicts and merge

**Pull request merged**
