### PR TITLE
feat: use pagination in transaction inputs/outputs list

### PR DESCRIPTION
**Pull request by zhangyouxin**
Resolves: https://github.com/Magickbase/ckb-explorer-public-issues/issues/484

### CODE REVIEW

**Comment by Keith-CY** [comment]
Please add reviewers if this PR is ready for review

**Comment by WhiteMinds** [comment]
image

The current design leads to the instant loading of a large number of inputs/outputs requests on the address page. The logic here needs to be redesigned.

I suggest treating `address_transactions` as a special case where the transaction model under this interface has trimmed displayInputs/displayOutputs and inputsCount/outputsCount fields.

@zhangyouxin @Keith-CY What do you think about it?

**Comment by Keith-CY** [comment]
> image
> 
> The current design leads to the instant loading of a large number of inputs/outputs requests on the address page. The logic here needs to be redesigned.
> 
> I suggest treating `address_transactions` as a special case where the transaction model under this interface has trimmed displayInputs/displayOutputs and inputsCount/outputsCount fields.
> 
> @zhangyouxin @Keith-CY @Daryl-L What do you think about it?
> 
> ### EDITED
> Pages like `DAO`, `BlockDetail`, and others that may contain a large number of transactions will also encounter this issue. Perhaps we need to provide minimal display purposes for displayInputs and displayOutputs for all interfaces.

Agreed, `inputs` and `outputs` of each transaction could be truncated to reduce the loading time.

**Comment by rabbitz** [comment]
> The current design leads to the instant loading of a large number of inputs/outputs requests on the address page. The logic here needs to be redesigned.
> 
> I suggest treating `address_transactions` as a special case where the transaction model under this interface has trimmed displayInputs/displayOutputs and inputsCount/outputsCount fields.

The display cells here do not require paging because the transaction list uses caching, and the display cells of each transaction can return up to 10 items. Pagination is mentioned only in the transaction show page

**Comment by zhangyouxin** [comment]
So that we need to keep changes in `Transaction Page` and revert the changes in `Address Page`

**Comment by Keith-CY** [comment]
@Danie0918 @Sven-TBD please align this feature request

**Comment by Sven-TBD** [comment]
Information updated here:

Discussed with nan, the pagination feature is only about the transaction detail page.  cc @zhangyouxin

**Comment by Keith-CY** [comment]
How is this going

**Comment by zhangyouxin** [comment]
moved to https://github.com/Magickbase/ckb-explorer-frontend/pull/188

**Pull request closed without merging**
