### PR TITLE
chore: optimize halving countdown time calcu

### PR DESCRIPTION
**Pull request by PainterPuppets**
resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/483

### CODE REVIEW

**Comment by FrederLu** [comment]
After refreshing the page, the countdown appears twice with a difference of 2 to 3 minutes.

https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/28a59a94-0926-47ba-9298-b6513958c45d

**Comment by FrederLu** [comment]
The halving page countdown is missing sync. If you stay on the halved page for a long time, you will find that the countdown time will increase when you refresh the page.
The screenshot shows the countdown time comparison before and after refreshing.
image
image

**Comment by PainterPuppets** [comment]
> 1、The halving page countdown is missing sync. If you stay on the halved page for a long time, you will find that the countdown time will increase when you refresh the page. The screenshot shows the countdown time comparison(比较) before and after refreshing. image image
> 
> 2、When there is one minute left in the countdown, manually refresh the homepage multiple times. When the time is displayed with more than 30 seconds left, the page suddenly ends the countdown and enters the halving waiting state. It should be caused by inaccurate calculation of this time.

Adjusted the timing of calculating the average block time using the current epoch timestamp

**Comment by PainterPuppets** [comment]
> 1、After refreshing the page, the countdown appears twice with a difference of 2 to 3 minutes.
> 
>  2023-11-15.16.56.15.mov 
> 2、The buffering time after "Coming Soon" is displayed is much longer than 3S, about 20 seconds. image

Now the countdown time is calculated based on the predicted time, the predicted time may change when the block number is updated, so it's not a fixed time

**Comment by FrederLu** [comment]
> > 1、The halving page countdown is missing sync. If you stay on the halved page for a long time, you will find that the countdown time will increase when you refresh the page. The screenshot shows the countdown time comparison(比较) before and after refreshing. image image
> > 2、When there is one minute left in the countdown, manually refresh the homepage multiple times. When the time is displayed with more than 30 seconds left, the page suddenly ends the countdown and enters the halving waiting state. It should be caused by inaccurate calculation of this time.
> 
> Adjusted the timing of calculating the average block time using the current epoch timestamp


https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/f0d4370f-2fe4-4f7c-a963-e658daa927db

Pay attention to the last 10 seconds of the video.
Before and after manually refreshing the page, the `Current Epoch` remains unchanged, but the time increases by 3 minutes after the refresh. If the refresh interval is longer, the time difference will be larger.

**Comment by PainterPuppets** [comment]
> Pay attention to the last 10 seconds of the video.
> Before and after manually refreshing the page, the `Current Epoch` remains unchanged, but the time increases by 3 minutes after the refresh. If the refresh interval is longer, the time difference will be larger.

I've tracked this case, the main reason for the predicted time change when refreshing is the block average time change , which is somewhat related to the current block number, and since the explorer's tipheader doesn't grow uniformly, there may be some time gaps after refreshing, and this issue may lead to inaccuracy in the countdown for a few tens of seconds

Personally, I feel this may be acceptable

**Review by FrederLu — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
