### PR TITLE
feat: highlight search input result keyword

### PR DESCRIPTION
**Pull request by PainterPuppets**
image

resolve: https://github.com/Magickbase/ckb-explorer-public-issues/issues/511

### CODE REVIEW

**Comment by Keith-CY** [comment]
`US` is matched when keyword is `USD`
image

**Comment by PainterPuppets** [comment]
> `US` is matched when keyword is `USD` image

The search results are provided by the backend, and the matching fields include "description", and I'm guessing "USD" is included in "description".

This pr is matching that string and highlighting it in the frontend, I can change it if it means that the frontend doesn't want to highlight `us` when typing `usd`, but if it doesn't want to display this search result, might have to change the backend.

**Comment by Keith-CY** [comment]
> > `US` is matched when keyword is `USD` image
> 
> The search results are provided by the backend, and the matching fields include "description", and I'm guessing "USD" is included in "description".
> 
> This pr is matching that string and highlighting it in the frontend, I can change it if it means that the frontend doesn't want to highlight `us` when typing `usd`, but if it doesn't want to display this search result, might have to change the backend.

But in this case `B*US*` should not be partially highlighted

**Comment by Keith-CY** [comment]
> > > `US` is matched when keyword is `USD` image
> > 
> > 
> > The search results are provided by the backend, and the matching fields include "description", and I'm guessing "USD" is included in "description".
> > This pr is matching that string and highlighting it in the frontend, I can change it if it means that the frontend doesn't want to highlight `us` when typing `usd`, but if it doesn't want to display this search result, might have to change the backend.
> 
> But in this case `B*US*` should not be partially highlighted

Any update on this

**Comment by PainterPuppets** [comment]
> > > > `US` is matched when keyword is `USD` image
> > > 
> > > 
> > > The search results are provided by the backend, and the matching fields include "description", and I'm guessing "USD" is included in "description".
> > > This pr is matching that string and highlighting it in the frontend, I can change it if it means that the frontend doesn't want to highlight `us` when typing `usd`, but if it doesn't want to display this search result, might have to change the backend.
> > 
> > 
> > But in this case `B*US*` should not be partially highlighted
> 
> Any update on this

fixed it

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @FrederLu

**Comment by FrederLu** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/issues/511#issue-2059157479

image
image

When the mouse is hovering, in addition to the matching information being highlighted, other information does not need to be highlighted.

---
image
image
The red line in the screenshot should be highlighted (the first point of the match), but it is not, while the later points are.

**Comment by PainterPuppets** [comment]
> [Magickbase/ckb-explorer-public-issues#511 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/511#issue-2059157479)
> 
> image image
> When the mouse is hovering, in addition to the matching information being highlighted, other information does not need to be highlighted.
> 
> image image The red line in the screenshot should be highlighted (the first point of the match), but it is not, while the later points are.
> image The data in the search results box is abnormal. Name information that matches the input information should be displayed, with matching data highlighted.
> image
> If there is no corresponding data match, the data should not be displayed in the result information.

Problems 1 and 2 have been fixed, regarding the last two points, the search results are returned by the back-end, if want to change the search fields and logic, may need to collaborate with the back-end developers.

**Comment by FrederLu** [comment]
> > [Magickbase/ckb-explorer-public-issues#511 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/511#issue-2059157479)
> > image image
> > When the mouse is hovering, in addition to the matching information being highlighted, other information does not need to be highlighted.
> > image image The red line in the screenshot should be highlighted (the first point of the match), but it is not, while the later points are.
> > image The data in the search results box is abnormal. Name information that matches the input information should be displayed, with matching data highlighted.
> > image
> > If there is no corresponding data match, the data should not be displayed in the result information.
> 
> Problems 1 and 2 have been fixed, regarding the last two points, the search results are returned by the back-end, if want to change the search fields and logic, may need to collaborate with the back-end developers.


The fixed problem will be verified later, but now the page cannot be opened, please confirm.

` regarding the last two points, the search results are returned by the back-end, if want to change the search fields and logic, may need to collaborate with the back-end developers.`

image
Using the API of `Testnet`, I saw that there is information related to the name, but the page displays the information of `symbol`. You can check with your backend colleagues to confirm.

**Comment by PainterPuppets** [comment]
> Using the API of `Testnet`, I saw that there is information related to the name, but the page displays the information of `symbol`. You can check with your backend colleagues to confirm.



> > > [Magickbase/ckb-explorer-public-issues#511 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/511#issue-2059157479)
> > > image image
> > > When the mouse is hovering, in addition to the matching information being highlighted, other information does not need to be highlighted.
> > > image image The red line in the screenshot should be highlighted (the first point of the match), but it is not, while the later points are.
> > > image The data in the search results box is abnormal. Name information that matches the input information should be displayed, with matching data highlighted.
> > > image
> > > If there is no corresponding data match, the data should not be displayed in the result information.
> > 
> > 
> > Problems 1 and 2 have been fixed, regarding the last two points, the search results are returned by the back-end, if want to change the search fields and logic, may need to collaborate with the back-end developers.
> 
> The fixed problem will be verified later, but now the page cannot be opened, please confirm.
> 
> ` regarding the last two points, the search results are returned by the back-end, if want to change the search fields and logic, may need to collaborate with the back-end developers.`
> 
> image
> Using the API of `Testnet`, I saw that there is information related to the name, but the page displays the information of `symbol`. You can check with your backend colleagues to confirm.

The display logic for previous searches was the same, `full_name` is more like a complementary name and `symbol` is a commonly used name, like `USD Tether` and `USDT`, maybe most people use the latter more often?

About search results, most search engines support many fields, it seems to me that searching for both `full_name` and `symbol` and `description` doesn't seem to be a problem?

**Comment by FrederLu** [comment]
image
image

When matching to the middle part of the character, the beginning part of the character seems to be compressed, see the pattern below in the screenshot.

**Comment by PainterPuppets** [comment]
> image image image
> When matching to the middle part of the character, the beginning part of the character seems to be compressed, see the pattern below in the screenshot.

fixed

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
