### PR TITLE
feat(live-cell): add link to asset name in live cell

### PR DESCRIPTION
**Pull request by Daryl-L**
https://github.com/Magickbase/ckb-explorer-public-issues/issues/640#issuecomment-2132601398

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqgrezkgm7vern8tujsed9g4je2wdr8hwkcye7vx8
image
image
1、Click to jump to the 404 page.

---
https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qpyn2yx4f6q4vydxgwhe0ddvjwlmk3wac24wpukuala0xsytfl8u6q2tqqqqqyqqqqqrqqqqqqcsqqqq6gmkrvmyyyrntsvuvptp6gflkwl2ut7kzun5xuv7la5jpcpqh2kqz9sqqqqqqq0a38txvlwdm9gaqu2y2q4v2xfg6jx3h5gyqqqqqqqqqqqqqqqqqqvkp6qzqqa2rwlg
image
image

image

2、The page after the jump displays abnormally.

https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qqlpadldfqym94sx2zlfdfq2h776lvlmjs4hkdlvwuy7vn3v6zncxqtr42shglgqcdjx0tc568d08qxz9seeasc4sxzh8

https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq85apn2vnk482lxg8p3uk30r78srnc0aqvyssuun
image

https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq9vrrzpflq9ec7gewjac09hxy0p4xxtvrcq2ahl7
image

**Comment by Daryl-L** [comment]
> https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vqgrezkgm7vern8tujsed9g4je2wdr8hwkcye7vx8 image image 1、Click to jump to the 404 page.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qpyn2yx4f6q4vydxgwhe0ddvjwlmk3wac24wpukuala0xsytfl8u6q2tqqqqqyqqqqqrqqqqqqcsqqqq6gmkrvmyyyrntsvuvptp6gflkwl2ut7kzun5xuv7la5jpcpqh2kqz9sqqqqqqq0a38txvlwdm9gaqu2y2q4v2xfg6jx3h5gyqqqqqqqqqqqqqqqqqqvkp6qzqqa2rwlg image image
> 
> image
> 2、The page after the jump displays abnormally.
> 
> https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qqlpadldfqym94sx2zlfdfq2h776lvlmjs4hkdlvwuy7vn3v6zncxqtr42shglgqcdjx0tc568d08qxz9seeasc4sxzh8
> 
> https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq85apn2vnk482lxg8p3uk30r78srnc0aqvyssuun image
> 
> https://ckb-explorer-frontend-in-magickbase-repo-fbzmjt7iq-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq9vrrzpflq9ec7gewjac09hxy0p4xxtvrcq2ahl7 image

The typehash from the `account api` and `live cell api` are different for nft. Could you check it out? @zmcNotafraid

**Comment by Daryl-L** [comment]
Done, and the link has been updated

**Comment by FrederLu** [comment]
> Done, and the link has been updated



https://ckb-explorer-frontend-in-magickbase-repo-jp501tb8s-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq85apn2vnk482lxg8p3uk30r78srnc0aqvyssuun

https://github.com/user-attachments/assets/3184c574-72dc-4ac9-b4dd-ab9d48c3bda0

1、When sliding to the next page on the live cells tab, the page becomes abnormal.

---
https://ckb-explorer-frontend-in-magickbase-repo-jp501tb8s-magickbase.vercel.app/address/ckt1qpvvtay34wndv9nckl8hah6fzzcltcqwcrx79apwp2a5lkd07fdxxq0l47eahymhw604kkdllakd9nu59g62k9c53tleu

https://github.com/user-attachments/assets/b9b3082b-6f6a-4a86-a779-6a022b704de3

2、The API prompts 404. At the same time, when the page shows that data cannot be obtained, there is also a loading style on it.

---

https://ckb-explorer-frontend-in-magickbase-repo-jp501tb8s-magickbase.vercel.app/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8x4293fhsqwrj8q3kx8qlsj4d4vzpwjsunwy220

3、When you click the `Live Cells` tab, the page displays an abnormality.

**Comment by FrederLu** [comment]
>2、The API prompts 404. At the same time, when the page shows that data cannot be obtained, there is also a loading style on it.

This problem still exists, please confirm.

---
https://ckb-explorer-frontend-in-magickbase-repo-4kcn5e4af-magickbase.vercel.app/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfhw0xngm6d7vlfq6avlghle86emcjd7wcqzeta4
image
image

Clicking on the data page in the red box in the screenshot will jump abnormally.

**Comment by Daryl-L** [comment]
> > 2、The API prompts 404. At the same time, when the page shows that data cannot be obtained, there is also a loading style on it.
> 
> This problem still exists, please confirm.

done

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
