### PR TITLE
fix(digest): mobile abnormal digest padding

### PR DESCRIPTION
**Pull request by Daryl-L**
https://github.com/Magickbase/ckb-explorer-public-issues/issues/648

### CODE REVIEW

**Comment by FrederLu** [comment]
image

https://ckb-explorer-frontend-in-magickbase-repo-4fm95lsnx-magickbase.vercel.app/transaction/0x5639d2f490a742b81ef01743cba7096b95187bc9da0d38025fb0261463c82d87

image
image


Comparing the UI screenshots in the issue, problems 2 and 3 still exist.If one line cannot be displayed, multiple lines must be displayed on the mobile terminal.
please confirm.

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a check @FrederLu

**Comment by FrederLu** [comment]
https://ckb-explorer-frontend-in-magickbase-repo-pzx1y3ne9-magickbase.vercel.app/transaction/0x6d5ae8a083158e2d9945dd3d43b6c9d2e9ebb1b2b5fa41b3a0d1042d314d2f29
image
The data for `Seal Tx On Bitcoin` requires the use of system colors.

**Comment by FrederLu** [comment]
> https://ckb-explorer-frontend-in-magickbase-repo-pzx1y3ne9-magickbase.vercel.app/transaction/0x6d5ae8a083158e2d9945dd3d43b6c9d2e9ebb1b2b5fa41b3a0d1042d314d2f29 image The data for `Seal Tx On Bitcoin` requires the use of system colors.

This problem still exists.

**Pull request merged**
