### PR TITLE
feat: show warning icon when inscription exist same symbol

### PR DESCRIPTION
**Pull request by zmcNotafraid**
Display a warning icon if an inscription collection uses a name which has been used by formerly issued inscriptions.

Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/527

---

Preview: https://ckb-explorer-frontend-in-magickbase-repo-git-0bf4f1-magickbase.vercel.app/inscriptions

### CODE REVIEW

**Comment by Keith-CY** [comment]
The icon should be outside the `underline` zone

UI Design
image

Preview
image

**Comment by zmcNotafraid** [comment]
> The icon should be outside the `underline` zone
> 
> UI Design image
> 
> Preview image

image

**Comment by FrederLu** [comment]
image
image
image
image
The style and UI during mouse hover are inconsistent.

**Comment by FrederLu** [comment]
image

According to the creation order, it is found that the first created `CKBI` also has a prompt mark. This is not what was expected.

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
