### PR TITLE
feat: set start point of selection of avg-block-time 1%

### PR DESCRIPTION
**Pull request by Keith-CY**
Selection starts from 1% because the avg block time is extremely high on blockchain launch

Ref: https://github.com/nervosnetwork/ckb-explorer-frontend/issues/1350

### CODE REVIEW

**Comment by Keith-CY** [comment]
BTW, I found the range of y-axis doesn't adjust itself along with moving the x-axis selection, possibly due to being frozen https://github.com/Magickbase/ckb-explorer-public-issues/issues/461#issuecomment-1793359738

**Comment by Keith-CY** [comment]
> BTW, I found the range of y-axis doesn't adjust itself along with moving the x-axis selection, possibly due to being frozen [Magickbase/ckb-explorer-public-issues#461 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/461#issuecomment-1793359738)

The y-axis doesn't scale because its range is set manually, fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/137/commits/231e972e29faeb1659699ee0d6c9a51b442a6e31

**Comment by WhiteMinds** [comment]
I think this might not be as expected:

origin:

image

after https://github.com/Magickbase/ckb-explorer-frontend/commit/231e972e29faeb1659699ee0d6c9a51b442a6e31

image

**Review by WhiteMinds — CHANGES_REQUESTED** [review]
Need to Confirm.

**Comment by Keith-CY** [comment]
> I think this might not be as expected:
> 
> origin:
> 
> image
> 
> after [231e972](https://github.com/Magickbase/ckb-explorer-frontend/commit/231e972e29faeb1659699ee0d6c9a51b442a6e31)
> 
> image

The preview is 

> I think this might not be as expected:
> 
> origin:
> 
> image
> 
> after [231e972](https://github.com/Magickbase/ckb-explorer-frontend/commit/231e972e29faeb1659699ee0d6c9a51b442a6e31)
> 
> image

The charts are slightly different at the left end

image


And I can see the selection is updated
image

**Comment by WhiteMinds** [comment]
> And I can see the selection is updated

I dragged them into the same range, which means the data displayed should be consistent.

**Comment by Keith-CY** [comment]
> > And I can see the selection is updated
> 
> I dragged them into the same range, which means the data displayed should be consistent.

It's probably caused by being frozen if the chart is not updated during expanding the selection, which should be solved by https://github.com/Magickbase/ckb-explorer-frontend/pull/138

**Comment by WhiteMinds** [comment]
I avoided the part where the tooltip error caused the table to freeze.

https://github.com/Magickbase/ckb-explorer-frontend/assets/9160743/4f3d26ae-06df-413b-b953-173592f50d44

**Comment by Keith-CY** [comment]
> I avoided the part where the tooltip error caused the table to freeze.
> 
>  Recording.2023-11-07.144429.mp4

The range of the weekly moving avg is auto-adjusted, so the ranges are different

**Review by WhiteMinds — APPROVED** [review]
> The range of the weekly moving avg is auto-adjusted, so the ranges are different

If this is as expected, then there is no problem.

**Comment by Keith-CY** [comment]
> > The range of the weekly moving avg is auto-adjusted, so the ranges are different
> 
> If this is as expected, then there is no problem.

The chart is hard to read even being scaled when range auto-adjustment is not enabled. And this PR is to move outliers out by default, so the fluctuation of trending can be clear. So I removed the fixed `min` and `max`

**Pull request merged**
